using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IOBusMonitorLib
{
    /// <summary>
    /// POCO entity that mirrors a row in the <c>MeasurementData</c> table
    /// generated by <see cref="DataStorageService"/>.
    /// </summary>
    [Table("MeasurementData")]
    public class MeasurementData
    {
        /// <summary>Auto-increment primary key.</summary>
        [Key]
        public long Id { get; set; }

        /// <summary>Timestamp when the value was recorded.</summary>
        public DateTime Timestamp { get; set; }

        /// <summary>Foreign key to the device.</summary>
        public int DeviceId { get; set; }

        /// <summary>Foreign key to the measuring point.</summary>
        public int PointId { get; set; }

        /// <summary>Foreign key to the measurement definition.</summary>
        public int MeasurementId { get; set; }

        /// <summary>Human-readable device name.</summary>
        [StringLength(50)]
        public string DeviceName { get; set; }

        /// <summary>Human-readable point name.</summary>
        [StringLength(50)]
        public string PointName { get; set; }

        /// <summary>Measurement name (e.g. “Temperature”).</summary>
        [StringLength(50)]
        public string MeasurementName { get; set; }

        /// <summary>Numeric value.</summary>
        public double Value { get; set; }

        /// <summary>Physical unit (°C, kPa, …).</summary>
        [StringLength(10)]
        public string Unit { get; set; }

        /// <summary>
        /// Type of protocol / device family the point belongs to.
        /// </summary>
        public PointType PointType { get; set; }
    }
}
